### ISSUE TITLE
I can not get balance !!

### ISSUE THREAD

**Issue by tomjawhoon** [ico-busses/token-transfer-dapp#36]

**Comment by adibas03** [comment]
Hi @tomjawhoon 
Can you better describe your issue, So, I can help with resolving it.  

* What is contract address  
* What network: Mainnet, Ropsten, Rinkeby, Kovan  
* What error do you get  
* What browser are you on

**Comment by tomjawhoon** [comment]
I can do it but can i continue to develop my project? because I am interested in cryptocurrency and ERC20 thank you :")

**Comment by adibas03** [comment]
Sure,
Yes, I guess,
Great to see another person interested in development on ERC20.
Thank you for reaching out.
