### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by r00ts3tors** [ico-busses/token-transfer-dapp#64]
I have install on my vps and my localhost, still get some error like : 
                               images/contractLogos/wed.png     259 KiB          [emitted]
                              images/contractLogos/weth.png    3.59 KiB          [emitted]
                       images/contractLogos/wibson-logo.png    2.82 KiB          [emitted]
                        images/contractLogos/wings_logo.svg    2.25 KiB          [emitted]
                       images/contractLogos/wyvern-logo.svg    3.93 KiB          [emitted]
                       images/contractLogos/xaurum_logo.svg    5.39 KiB          [emitted]
                          images/contractLogos/yggdrash.svg    15.6 KiB          [emitted]
                           images/contractLogos/zilliqa.svg    3.72 KiB          [emitted]
                                   images/icons/favicon.ico    21.2 KiB          [emitted]
                              images/icons/logo-colored.svg    2.82 KiB          [emitted]
                    images/icons/logo-white-transparent.svg    4.02 KiB          [emitted]
                                images/icons/logo-white.svg    2.08 KiB          [emitted]
                              images/icons/wallet-solid.svg   522 bytes          [emitted]
                                                 index.html    1.19 KiB          [emitted]
                                                 js/main.js    14.3 MiB    main  [emitted]  main
logo-white-transparent.svg?8f355c24f522046880767cdaa6da6715    4.02 KiB          [emitted]
Entrypoint main = js/main.js
[0] multi (webpack)-dev-server/client?https://localhost:8080 (webpack)/hot/dev-server.js @babel/polyfill ./src/main.js 64 bytes {main} [built]
[./node_modules/@babel/polyfill/lib/index.js] 1.68 KiB {main} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 1.58 KiB {main} [built]
[./node_modules/core-js/library/fn/global.js] 1.1 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:8080] (webpack)-dev-server/client?https://localhost:8080 5.31 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 4.54 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 2.56 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 3.94 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 1.97 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 2.63 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 1.44 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 1.21 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 2.6 KiB {main} [built]
[./src/main.js] 1.24 KiB {main} [built]
    + 1082 hidden modules

WARNING in ./src/services/index.js 6:0-39
"export 'all' (reexported as 'Utils') was not found in './utils'
 @ ./src/components/Layout.js
 @ ./src/components/Home.js
 @ ./src/components/index.js
 @ ./src/main.js
 @ multi @babel/polyfill ./src/main.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/www/main.html] 1.36 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 1.47 KiB {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 1.49 KiB {0} [built]
ℹ ｢wdm｣: Compiled with warnings.

I used 
1. Clone repo
2. do npm install
3. npm start

any solution or any code need for fix it thanks for respond

**Comment by adibas03** [comment]
There is no error from that log, only a warning which will be taken care of soon.
This should not stop the Dapp from running, though.
Follow the steps
- clone repo
- run `npm install`
- run `npm start`
- Open your browser to `https://localhost:8080`

**Comment by r00ts3tors** [comment]
Thanks you for commandted
