### ISSUE TITLE
Need Guide For installation for try

### ISSUE THREAD

**Issue by r00ts3ctors** [ico-busses/token-transfer-dapp#65]
Hallo, I need some methode guide for installation step by step and what code need for edit for make this repo will run well

**Comment by adibas03** [comment]
Follow the steps
- clone repo
- run `npm install`
- run `npm start`
- Open your browser to `https://localhost:8080`

If you do not want to use `https`,
set https to  `false` in `webpack.config.js`
https://github.com/ico-busses/token-transfer-dapp/blob/dev/webpack.config.js#L23

**Comment by r00ts3tors** [comment]
Thanks you brohta, thanks you that work  used https://localhost:8080 that run i will try and thanks you

**Comment by adibas03** [comment]
For Vps,
you need to first build the app using `npm run build`
the copy the content of `dist` folder to the public folder of the vps.
then you should be able to access it from the `vps_url: vps_port`

**Comment by r00ts3ctors** [comment]
thanks you for respond i will try it
